project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true


editor: visual

