project:
  type: website
  output-dir: docs

website:
  title: "Sea Level Meeting"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Abstracts Book"
        href: abstracts/index.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true


editor: visual

