# Past and Future Sea-level Changes in Cork Harbour Region: ‘It’s All For the Birds’!?

**Author:** Robert Devoy


**Abstract:**  
Cork Harbour constitutes the outer and the main part of the estuary of the River Lee. It contains long (>28m thick) sedimentary sequences of gravels, sands, silts and clays of Late Quaternary to late Holocene ages. Radiocarbon dating of the base of these sediments south of Spike Island (the Curlane Bank) has given a date of c.8,000 BP at heights of c.-12m ODM for postglacial sea-level rise and the marine inundation of the region. Stratigraphic and dating work at the Harper’s Island wetlands, in the back harbour area, has recently given new detail to the later Holocene phases of this flooding. Spring tidal ranges in the estuary reach commonly values of c.3.5 - 4m (meso- to macro-tidal), with storm surges raising this to c.5m height in Cork city and the inner estuary; with the frequent overtopping of river walls, port jetties and sea defences. This marine water blockage of the river has historically created major flooding problems for Cork city centre. Under future climate change and sea level rise, this surge flooding forms a significant vulnerability for the city and the adjacent harbour lowlands and has generated a current controversy about appropriate policy and approaches for coastal flood management control, both for Cork and nationally.
