# Sea level rise and storm surges around Ireland: Climate modelling at Met Éireann

**Author:** Tido Semmler

**Affiliation:** Met Éireann

**Abstract:**\
Observed regional differences in sea level rise around Ireland, with some coastal urban centres experiencing rates exceeding global averages, underscore the critical need for future projections at regional and local scales to inform robust adaptation measures. The lack of high-resolution local sea level projections suitable for detailed adaptation planning has been identified as a significant gap in Ireland’s Climate Change Assessment. The National Framework for Climate Services (NFCS) supports the imperative for developing such local projections to meet stakeholder requirements. Addressing this challenge necessitates a sophisticated multi-scale modelling approach. This ranges from refining global climate models (10-100 km), with a particular focus on achieving realistic Greenland and Antarctic melt input, to deploying regional coupled climate models around Ireland that include tidal dynamics (1-10 km), and finally to implementing local coastal inundation models for densely populated areas like Dublin Bay (10-100 m). Met Éireann plans to employ two postdoctoral researchers to work on modelling sea level rise, storm surge, and coastal flooding in collaboration with the Irish Centre for High End Computing (ICHEC), the Marine Institute (MI), Trinity College Dublin (TCD), the Alfred Wegener Institute for Polar and Marine Research (AWI), the Danish Meteorological Institute (DMI) as well as with European projects. An initial assessment of global climate model simulated Greenland meltwater input shows that the meltwater input is underestimated in global climate model simulations in the last two decades in which a substantial increase of Greenland melt has been observed. This has been corrected in sensitivity simulations, and further refinements of the simulations are subject of ongoing development.
