---
title: "Abstracts"
date: "May 2025"
format:
  html: default
---

Welcome to the 8th Annual Sea Level Meeting Book of Abstracts. This collection includes the abstracts of all oral presentations.

Use the links below to browse abstracts by title.

------------------------------------------------------------------------

**Conference Dates:** May 21–22, 2025\
**Location:** Maynooth University

1: [Near-term sea-level projections for Southeast Asia](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract1.html)

2: [A global analysis on coastal migration due to sea-level rise](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract2.html)

3: [Sea level rise and storm surges around Ireland: Climate modelling at Met Éireann](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract3.html)

4: [Past and Future Sea-level Changes in Cork Harbour Region: ‘It’s All For the Birds’!?](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract7.html)

5: [Bayesian Hierarchical Spatio-Temporal Model for Extreme Sea-Level Prediction](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract9.html)

6: [Storm Éowyn: What Can Be Learned from Irish Tidal Gauges](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract10.html)

7: [Integrating upper beach morphodynamics into future storm risk: A storyline approach under sea level rise](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract12.html)

8: [Evaluating the sensitivity of threshold selection in Extreme value methods](https://ncahill89.github.io/SeaLevelMeeting/abstracts/abstract13.html)


